// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SqlProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("SqlProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing SqlProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SqlProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "SqlProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing SqlProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
